#########################################################################
#
#                 -- Generated with omgcmd --
#      (do not edit unless you know what you're doing)
#
#########################################################################

# Copyright (C) 2022 One More Game - All Rights Reserved
# Unauthorized copying of this file, via any medium is strictly prohibited
# Proprietary and confidential

# omgcmd { overwrite: false }

# imported fork
resource "github_repository" "this" {
  name = "UnityNuGet"

  description   = "Provides a service to install NuGet packages into a Unity project via the Unity Package Manager"
  has_downloads = true
  has_projects  = true
}

resource "github_repository_webhook" "this" {
  repository = github_repository.this.name
  events     = ["deployment", "pull_request", "push"]

  configuration {
    # Payload URL generated by BuildKite when creating a new pipeline
    url          = buildkite_pipeline.this.webhook_url
    content_type = "application/json"
    insecure_ssl = false
  }
}
